### ISSUE TITLE
pyrocko.gf.store_ext.StoreExtError: INDEX_OUT_OF_BOUNDS for SARScape data

### ISSUE THREAD

**Issue by ranneylxr** [hvasbath/beat#147]
Hi there,

It is my first time to run BEAT software using deformation field generated by **SARScape.** Then there was a **INDEX_OUT_OF_BOUNDS** error even I set the source_depth_max and source_distance_radius at very large value.

**And BEAT works well with deformation generate by other software, such as Mintpy.**

The following are details:
**--Data (producted by SARScape)**
```
*reflat_disp in cm unit
*reflat_disp_ALOS
*reflat_disp_ILOS
The projection are UTM. 
```
Everything is OK when I used **kite t**o do quadtree downsampling and used` beat import` to generate the *.pkl dataset.

**-- Beat**
_version: 2.0.4_
I have used this version  to process several events succussfully.

**--Parameters in config_geometry.yaml:**
```
problem_config: !beat.ProblemConfig
  mode: geometry
  source_types:
  - RectangularSource
  stf_type: HalfSinusoid
  decimation_factors:
    geodetic: 4
  n_sources:
  - 1
  datatypes:
  - geodetic
  hyperparameters:
    h_SAR: !beat.heart.Parameter
      name: h_SAR
      form: Uniform
      lower:
      - -2.0
      upper:
      - 6.0
      testvalue:
      - 2.0
  priors:
    depth: !beat.heart.Parameter
      name: depth
      form: Uniform
      lower:
      - 0.0
      upper:
      - 30.0
      testvalue:
      - 13.0
    dip: !beat.heart.Parameter
      name: dip
      form: Uniform
      lower:
      - 0.0
      upper:
      - 90.0
      testvalue:
      - 63.0
    east_shift: !beat.heart.Parameter
      name: east_shift
      form: Uniform
      lower:
      - -22.0
      upper:
      - 28.0
      testvalue:
      - -8.0
    length: !beat.heart.Parameter
      name: length
      form: Uniform
      lower:
      - 0.0
      upper:
      - 30.0
      testvalue:
      - 11.0
    north_shift: !beat.heart.Parameter
      name: north_shift
      form: Uniform
      lower:
      - -7.0
      upper:
      - 50.0
      testvalue:
      - 0.0
    rake: !beat.heart.Parameter
      name: rake
      form: Uniform
      lower:
      - -180.0
      upper:
      - 0.0
      testvalue:
      - -90.0
    slip: !beat.heart.Parameter
      name: slip
      form: Uniform
      lower:
      - 0.0
      upper:
      - 15.0
      testvalue:
      - 1.7000000000000002
    strike: !beat.heart.Parameter
      name: strike
      form: Uniform
      lower:
      - 0.0
      upper:
      - 360.0
      testvalue:
      - 36.0
    width: !beat.heart.Parameter
      name: width
      form: Uniform
      lower:
      - 0.0
      upper:
      - 30.0
      testvalue:
      - 9.0
  hierarchicals:
    SenAT_coseismic_azimuth_ramp: !beat.heart.Parameter
      name: SenAT_coseismic_azimuth_ramp
      form: Uniform
      lower:
      - -0.005
      upper:
      - 0.005
      testvalue:
      - 0.0
    SenAT_coseismic_offset: !beat.heart.Parameter
      name: SenAT_coseismic_offset
      form: Uniform
      lower:
      - -0.05
      upper:
      - 0.05
      testvalue:
      - 0.0
    SenAT_coseismic_range_ramp: !beat.heart.Parameter
      name: SenAT_coseismic_range_ramp
      form: Uniform
      lower:
      - -0.005
      upper:
      - 0.005
      testvalue:
      - 0.0
    SenDT493_coseismic_azimuth_ramp: !beat.heart.Parameter
      name: SenDT493_coseismic_azimuth_ramp
      form: Uniform
      lower:
      - -0.005
      upper:
      - 0.005
      testvalue:
      - 0.0
    SenDT493_coseismic_offset: !beat.heart.Parameter
      name: SenDT493_coseismic_offset
      form: Uniform
      lower:
      - -0.05
      upper:
      - 0.05
      testvalue:
      - 0.0
    SenDT493_coseismic_range_ramp: !beat.heart.Parameter
      name: SenDT493_coseismic_range_ramp
      form: Uniform
      lower:
      - -0.005
      upper:
      - 0.005
      testvalue:
      - 0.0
    SenDT499_coseismic_azimuth_ramp: !beat.heart.Parameter
      name: SenDT499_coseismic_azimuth_ramp
      form: Uniform
      lower:
      - -0.005
      upper:
      - 0.005
      testvalue:
      - 0.0
    SenDT499_coseismic_offset: !beat.heart.Parameter
      name: SenDT499_coseismic_offset
      form: Uniform
      lower:
      - -0.05
      upper:
      - 0.05
      testvalue:
      - 0.0
    SenDT499_coseismic_range_ramp: !beat.heart.Parameter
      name: SenDT499_coseismic_range_ramp
      form: Uniform
      lower:
      - -0.005
      upper:
      - 0.005
      testvalue:
      - 0.0
geodetic_config: !beat.GeodeticConfig
  types:
    SAR: !beat.SARDatasetConfig
      datadir: /data/insarlab/BEAT/Dingri/data/
      names:
      - SenAT_coseismic
      - SenDT493_coseismic
      - SenDT499_coseismic
  noise_estimator: !beat.GeodeticNoiseAnalyserConfig
    structure: import
    max_dist_perc: 0.2
  interpolation: multilinear
  corrections_config: !beat.GeodeticCorrectionsConfig
    euler_poles:
    - !beat.EulerPoleConfig
      enabled: false
    ramp: !beat.RampConfig
      dataset_names:
      - SenAT_coseismic
      - SenDT493_coseismic
      - SenDT499_coseismic
      enabled: true
    strain_rates:
    - !beat.StrainRateConfig
      enabled: false
  dataset_specific_residual_noise_estimation: false
  gf_config: !beat.GeodeticGFConfig
    reference_model_idx: 0
    n_variations:
    - 0
    - 1
    store_superdir: /data/insarlab/GF/Dingri/
    earth_model_name: ak135-f-continental.f
    nworkers: 20
    use_crust2: true
    replace_water: true
    source_depth_min: 0.0
    source_depth_max: 100.0
    source_depth_spacing: 1.0
    source_distance_radius: 1000.0
    source_distance_spacing: 1.0
    error_depth: 0.1
    error_velocities: 0.1
    depth_limit_variation: 600.0
    version: ''
    code: psgrn
    sample_rate: 1.1574074074074073e-05
    sampling_interval: 1.0
    medium_depth_spacing: 1.0
```
**-- Error message:**
```
geodetic     - INFO     Number of geodetic datasets: 3 
geodetic     - INFO     Initialising corrections ...
heart        - INFO     Setting up Ramps correction for SenAT_coseismic
heart        - INFO     Masking data for Ramps estimation!
heart        - INFO     Not correcting SenAT_coseismic for Euler Pole
heart        - INFO     Not correcting SenAT_coseismic for Strain Rate
heart        - INFO     Setting up Ramps correction for SenDT493_coseismic
heart        - INFO     Masking data for Ramps estimation!
heart        - INFO     Not correcting SenDT493_coseismic for Euler Pole
heart        - INFO     Not correcting SenDT493_coseismic for Strain Rate
heart        - INFO     Setting up Ramps correction for SenDT499_coseismic
heart        - INFO     Masking data for Ramps estimation!
heart        - INFO     Not correcting SenDT499_coseismic for Euler Pole
heart        - INFO     Not correcting SenDT499_coseismic for Strain Rate
geodetic     - INFO     Number of geodetic data points: 1058 
geodetic     - INFO     Initialising geometry geodetic composite ...
models       - INFO     ... Building Hyper model ...

geodetic     - INFO     Evaluating config for Ramps corrections for datasets...
geodetic     - INFO     Evaluating config for Euler Pole corrections for datasets...
geodetic     - INFO     No Euler Pole correction!
geodetic     - INFO     Evaluating config for Strain Rate corrections for datasets...
geodetic     - INFO     No Strain Rate correction!
geodetic     - INFO     Initialized 9 hierarchical parameters.
models       - INFO     Initialised hyperparameter h_SAR with size 1 
models       - INFO     Initialized 1 hyperparameters in total!
geodetic     - INFO     Retrieving geodetic data-covariances with structure "import" for SenAT_coseismic ...
geodetic     - INFO     Retrieving geodetic data-covariances with structure "import" for SenDT493_coseismic ...
geodetic     - INFO     Retrieving geodetic data-covariances with structure "import" for SenDT499_coseismic ...
Traceback (most recent call last):
  File "/opt/conda/envs/beatenv/bin/beat", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/conda/envs/beatenv/lib/python3.11/site-packages/beat/apps/beat.py", line 2441, in main
    globals()["command_" + command](args)
  File "/opt/conda/envs/beatenv/lib/python3.11/site-packages/beat/apps/beat.py", line 1061, in command_sample
    problem = load_model(project_dir, options.mode, options.hypers)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/beatenv/lib/python3.11/site-packages/beat/models/problems.py", line 920, in load_model
    problem.built_hyper_model()
  File "/opt/conda/envs/beatenv/lib/python3.11/site-packages/beat/models/problems.py", line 291, in built_hyper_model
    composite.update_llks(point)
  File "/opt/conda/envs/beatenv/lib/python3.11/site-packages/beat/models/geodetic.py", line 436, in update_llks
    results = self.assemble_results(point)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/beatenv/lib/python3.11/site-packages/beat/models/geodetic.py", line 214, in assemble_results
    processed_synts = self.get_synthetics(point)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/beatenv/lib/python3.11/site-packages/beat/models/geodetic.py", line 714, in get_synthetics
    displacements = heart.geo_synthetics(
                    ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/beatenv/lib/python3.11/site-packages/beat/heart.py", line 4198, in geo_synthetics
    response = engine.process(sources, targets)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/beatenv/lib/python3.11/site-packages/pyrocko/gf/seismosizer.py", line 5744, in process
    for ii_results, tcounters_static in process_static(
  File "/opt/conda/envs/beatenv/lib/python3.11/site-packages/pyrocko/gf/seismosizer.py", line 5247, in process_static
    base_statics, tcounters = engine.base_statics(
                              ^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/beatenv/lib/python3.11/site-packages/pyrocko/gf/seismosizer.py", line 5585, in base_statics
    base_statics = store_.statics(
                   ^^^^^^^^^^^^^^^
  File "/opt/conda/envs/beatenv/lib/python3.11/site-packages/pyrocko/gf/store.py", line 2084, in statics
    res = store_ext.store_calc_static(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pyrocko.gf.store_ext.StoreExtError: INDEX_OUT_OF_BOUNDS
```

Thank you！

**Comment by hvasbath** [comment]
Did you check here, issue number 6? https://pyrocko.org/beat/docs/current/faq.html
What is the extent of your data in Kite? DId you ensure units are consistent? In the config in beat distances/lengths are in km. Sorry for that!
What is the distance/extent of your GF store? Changing it in the config of beat only does not help, you need to rebuild the gfs.
See $store_superdir/store_name/config

**Comment by hvasbath** [comment]
That looks all ok.
Can you please upload the entire config_geometry.yaml? Can you please rerun with --log_level=debug. What is the command line you are executing?

**Comment by ranneylxr** [comment]
Ah, so the data should be in Geographic Lat/Lon projection? I checked the latitudes in geodetic_data.pkl and found the latitudes are wrong. **The correct latitudes should be in 28N to 29N, but the values in geodetic_data.pkl are between -59 to -60.**

The reason for converting Geographic Lat/Lon projection to UTM projection is when I used` Scene.import_data('') `to read *_disp generated by SARScape, there was an error `raise HeaderError(map info header is not consistent!")`. 

It seems that the KITE need `map_info` have 11 elements ( Geographic projection only have 9 elements.) and it seems that KITE also requires the projection should be in UTM?
Here is the code in the scene_io.py:
```
header.map_info = header.map_info.strip("{} ").split(", ")
if not len(header.map_info) == 11:
      raise HeaderError("`map info` header is not consistent!")
if header.map_info[0] != "UTM":
       raise HeaderError("`map info` is not UTM!")
```

**Comment by ranneylxr** [comment]
And the following is the output when I rerun with --loglevel=debug
```
pyrocko.gf.store_ext.StoreExtError: INDEX_OUT_OF_BOUNDS
filelock     - DEBUG    Attempting to acquire lock 139975339283152 on /root/.pytensor/compiledir_Linux-6.2--generic-x86_64-with-glibc2.36--3.11.11-64/.lock
filelock     - DEBUG    Lock 139975339283152 acquired on /root/.pytensor/compiledir_Linux-6.2--generic-x86_64-with-glibc2.36--3.11.11-64/.lock
filelock     - DEBUG    Attempting to release lock 139975339283152 on /root/.pytensor/compiledir_Linux-6.2--generic-x86_64-with-glibc2.36--3.11.11-64/.lock
filelock     - DEBUG    Lock 139975339283152 released on /root/.pytensor/compiledir_Linux-6.2--generic-x86_64-with-glibc2.36--3.11.11-64/.lock
```
Here is the total content of my config_geometry.yaml
```
--- !beat.BEATconfig
name: DingriEQ
date: '2025-01-07'
event: !pf.Event
  lat: 28.56
  lon: 87.47
  time: '2025-01-07 01:05:27.569999933'
  depth: 12000.0
  name: '202501070105A'
  magnitude: 7.116403576020531
  region: 'XIZANG'
  catalog: 'gCMT-Q'
  moment_tensor: !pf.MomentTensor
    mnn: -4.25e+18
    mee: 5.45e+19
    mdd: -5.03e+19
    mne: 5.49e+18
    mnd: -1.69e+18
    med: -4.59e+18
    strike1: 173.14793899411472
    dip1: 47.58586687546202
    rake1: -92.12667019710119
    strike2: 356.2992366967094
    dip2: 42.4573121817565
    rake2: -87.67396555504558
    moment: 5.3040225772521e+19
    magnitude: 7.116403576020531
  duration: 17.0
project_dir: /data/insarlab/BEAT/Dingri/DingriEQ
problem_config: !beat.ProblemConfig
  mode: geometry
  source_types:
  - RectangularSource
  stf_type: HalfSinusoid
  decimation_factors:
    geodetic: 4
  n_sources:
  - 1
  datatypes:
  - geodetic
  hyperparameters:
    h_SAR: !beat.heart.Parameter
      name: h_SAR
      form: Uniform
      lower:
      - -2.0
      upper:
      - 6.0
      testvalue:
      - 2.0
  priors:
    depth: !beat.heart.Parameter
      name: depth
      form: Uniform
      lower:
      - 0.0
      upper:
      - 30.0
      testvalue:
      - 13.0
    dip: !beat.heart.Parameter
      name: dip
      form: Uniform
      lower:
      - 0.0
      upper:
      - 90.0
      testvalue:
      - 63.0
    east_shift: !beat.heart.Parameter
      name: east_shift
      form: Uniform
      lower:
      - -22.0
      upper:
      - 28.0
      testvalue:
      - -8.0
    length: !beat.heart.Parameter
      name: length
      form: Uniform
      lower:
      - 0.0
      upper:
      - 30.0
      testvalue:
      - 11.0
    north_shift: !beat.heart.Parameter
      name: north_shift
      form: Uniform
      lower:
      - -7.0
      upper:
      - 50.0
      testvalue:
      - 0.0
    rake: !beat.heart.Parameter
      name: rake
      form: Uniform
      lower:
      - -180.0
      upper:
      - 0.0
      testvalue:
      - -90.0
    slip: !beat.heart.Parameter
      name: slip
      form: Uniform
      lower:
      - 0.0
      upper:
      - 15.0
      testvalue:
      - 1.7000000000000002
    strike: !beat.heart.Parameter
      name: strike
      form: Uniform
      lower:
      - 0.0
      upper:
      - 360.0
      testvalue:
      - 36.0
    width: !beat.heart.Parameter
      name: width
      form: Uniform
      lower:
      - 0.0
      upper:
      - 30.0
      testvalue:
      - 9.0
  hierarchicals:
    SenAT_coseismic_azimuth_ramp: !beat.heart.Parameter
      name: SenAT_coseismic_azimuth_ramp
      form: Uniform
      lower:
      - -0.005
      upper:
      - 0.005
      testvalue:
      - 0.0
    SenAT_coseismic_offset: !beat.heart.Parameter
      name: SenAT_coseismic_offset
      form: Uniform
      lower:
      - -0.05
      upper:
      - 0.05
      testvalue:
      - 0.0
    SenAT_coseismic_range_ramp: !beat.heart.Parameter
      name: SenAT_coseismic_range_ramp
      form: Uniform
      lower:
      - -0.005
      upper:
      - 0.005
      testvalue:
      - 0.0
    SenDT493_coseismic_azimuth_ramp: !beat.heart.Parameter
      name: SenDT493_coseismic_azimuth_ramp
      form: Uniform
      lower:
      - -0.005
      upper:
      - 0.005
      testvalue:
      - 0.0
    SenDT493_coseismic_offset: !beat.heart.Parameter
      name: SenDT493_coseismic_offset
      form: Uniform
      lower:
      - -0.05
      upper:
      - 0.05
      testvalue:
      - 0.0
    SenDT493_coseismic_range_ramp: !beat.heart.Parameter
      name: SenDT493_coseismic_range_ramp
      form: Uniform
      lower:
      - -0.005
      upper:
      - 0.005
      testvalue:
      - 0.0
    SenDT499_coseismic_azimuth_ramp: !beat.heart.Parameter
      name: SenDT499_coseismic_azimuth_ramp
      form: Uniform
      lower:
      - -0.005
      upper:
      - 0.005
      testvalue:
      - 0.0
    SenDT499_coseismic_offset: !beat.heart.Parameter
      name: SenDT499_coseismic_offset
      form: Uniform
      lower:
      - -0.05
      upper:
      - 0.05
      testvalue:
      - 0.0
    SenDT499_coseismic_range_ramp: !beat.heart.Parameter
      name: SenDT499_coseismic_range_ramp
      form: Uniform
      lower:
      - -0.005
      upper:
      - 0.005
      testvalue:
      - 0.0
geodetic_config: !beat.GeodeticConfig
  types:
    SAR: !beat.SARDatasetConfig
      datadir: /data/insarlab/BEAT/Dingri/data/
      names:
      - SenAT_coseismic
      - SenDT493_coseismic
      - SenDT499_coseismic
  noise_estimator: !beat.GeodeticNoiseAnalyserConfig
    structure: import
    max_dist_perc: 0.2
  interpolation: multilinear
  corrections_config: !beat.GeodeticCorrectionsConfig
    euler_poles:
    - !beat.EulerPoleConfig
      enabled: false
    ramp: !beat.RampConfig
      dataset_names:
      - SenAT_coseismic
      - SenDT493_coseismic
      - SenDT499_coseismic
      enabled: true
    strain_rates:
    - !beat.StrainRateConfig
      enabled: false
  dataset_specific_residual_noise_estimation: false
  gf_config: !beat.GeodeticGFConfig
    reference_model_idx: 0
    n_variations:
    - 0
    - 1
    store_superdir: /data/insarlab/GF/Dingri/
    earth_model_name: ak135-f-continental.f
    nworkers: 20
    use_crust2: true
    replace_water: true
    source_depth_min: 0.0
    source_depth_max: 500.0
    source_depth_spacing: 1.0
    source_distance_radius: 2000.0
    source_distance_spacing: 1.0
    error_depth: 0.1
    error_velocities: 0.1
    depth_limit_variation: 600.0
    version: ''
    code: psgrn
    sample_rate: 1.1574074074074073e-05
    sampling_interval: 1.0
    medium_depth_spacing: 1.0
    medium_distance_spacing: 10.0
sampler_config: !beat.SamplerConfig
  name: SMC
  backend: csv
  progressbar: true
  buffer_size: 5000
  buffer_thinning: 1
  parameters: !beat.SMCConfig
    tune_interval: 50
    check_bnd: true
    rm_flag: false
    n_jobs: 1
    n_steps: 100
    n_chains: 1000
    coef_variation: 1.0
    stage: 0
    proposal_dist: MultivariateNormal
    update_covariances: false
hyper_sampler_config: !beat.SamplerConfig
  name: Metropolis
  backend: csv
  progressbar: true
  buffer_size: 5000
  buffer_thinning: 1
  parameters: !beat.MetropolisConfig
    tune_interval: 50
    proposal_dist: Normal
    check_bnd: true
    rm_flag: false
    n_jobs: 20
    n_steps: 25000
    n_chains: 20
    thin: 2
    burn: 0.5
```
